apiVersion: apps/v1
kind: Deployment
metadata:
  name: service
spec:
  template:
    spec:
      containers:
        - name: service
          env:
          - name: DISCARD_QUOTA
            value: "0"
          - name: REJECT
            value: "0"