apiVersion: apps/v1
kind: Deployment
metadata:
  name: service
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        sidecar.istio.io/userVolumeMount: '[{"name":"lua-libs", "mountPath":"/var/lib/lua", "readonly":true}]'
    spec:
      volumes: []
      containers:
        - name: service
          env:
          - name: DISCARD_QUOTA
            value: "0"
          - name: REJECT
            value: "0"
          image: localhost:5000/minimal-service:v1.0.0
          ports:
          - containerPort: 9090
          livenessProbe:
            httpGet:
              path: /health
              port: 9090
            initialDelaySeconds: 3
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 9090
            initialDelaySeconds: 3
            periodSeconds: 5
          resources:
            requests:
              memory: "100Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          volumeMounts: []
      securityContext:
        runAsNonRoot: false

